language: generic
addons:
  apt:
    packages:
      - libc6:i386
      - libstdc++6:i386
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz
  - tar xf arduino-1.8.10-linux64.tar.xz
  - sudo mv arduino-1.8.10 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  # install required libs
  # install lib arduino not working in 1.6.5
  - arduino --install-library "ArduinoJson:6.16.1"
  - arduino --install-library "WebSockets:2.1.4"
  - arduino --install-library "NTPClient:3.2.0"
  - git clone -b development https://github.com/tzapu/WiFiManager /usr/local/share/arduino/libraries/WiFiManager
  # - install_library "https://github.com/tzapu/WiFiManager.git" "development" "WiFiManager"

  # install ESP8266
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  # - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --board esp8266:esp8266:generic:xtal=80,vt=flash,exception=legacy,ssl=all,ResetMethod=nodemcu,CrystalFreq=26,FlashFreq=40,FlashMode=dout,eesz=1M128,led=1,sdk=nonosdk_191024,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200 --save-prefs

  # set compile options
  # - arduino --pref "compiler.warning_level=all" --save-prefs

  # Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
script:
  # - cat $PWD/SmartLight-Firmware/SmartLight-Firmware.ino
  - arduino --verify "${PWD}/SmartLight-Firmware/SmartLight-Firmware.ino"